### PR TITLE
Fixed Sequential Feature Selector - unsupervised fit issue with docs and test update

### LINKED ISSUE #1: [19538] Fix the issue
Fix the issue by investigating the bug description, appropriate method and class definitions, and their intended purpose(s).

Time estimation: 3 hours

Acceptance tests:
- [x] run the original use case that displayed the incorrect behavior and show it runs as intended
- [x] edit the docstring documentation for the changed classes and methods to reflect the fixes (including changes to the parameters, behavior, return values, etc.)

### LINKED ISSUE #6: [19538] Design acceptance test suite
Write a test that shows the bug is fixed: that when we run `SequentialFeatureSelector.fit_transform` without the `y` label, there won't be an error, as expected.

Time estimation: 2 hours

Acceptance tests:
- [x] create a use case for SequentialFeatureSelector and run `fit_transform` without the `y` label
- [x] show that it runs without and error as expected

### PR DESCRIPTION
**Pull request by swarupsrini**
#### Reference Issues/PRs

Fixes issue 19538

#### What does this implement/fix? Explain your changes.
This fixes the issue where the calling the SequentialFeatureSelector's fit/fit_transform method with a 'y' label as in unsupervised learning results in an error. 

#### Any other comments?
If the 'y' label is not given, it is defaulted to None. The docstrings are also updated to reflect the fix and an additional test case has been implemented.

### CODE REVIEW

**Comment by ObaidaSaleh** [comment]
LGTM

**Review by ObaidaSaleh — APPROVED** [review]

**Review by HuIsJason — APPROVED** [review]
LGTM!

**Review by howardleung — APPROVED** [review]
**LGTM** 👍

**Review by jasoncndai — APPROVED** [review]
LGTM!

**Review by hemant3434 — APPROVED** [review]

**Pull request merged**
